### ISSUE TITLE
calculate_column_widths does not properly work w. colspan?

### ISSUE THREAD

**Issue by practicingruby** [practicingruby/prawn-layout#2]
See: http://github.com/blaxter/prawn-layout/commits/master

**Comment by practicingruby** [comment]
Pulled in one of those patches.  The other was too complicated and would have impacted performance.  Those interested, please show a reduced example of the problem and submit an alternative solution.

**Comment by blaxter** [comment]
It's complicated because calculate the correct value for column widths when colspan cells exist is complicated (and even more if you add rowspan cells to the scene).

How could a loop have impact on performance? Besides it's a loop only "doing things" when a colspan cell is found.

Anyway, that commit in fact has been rewritten in a branch where I've implemented rowspan, which is so much more complicated that this trivial thing, so I guess you don't wanna the patch neither.

**Comment by practicingruby** [comment]
I wasn't talking as much about the necessary complexity as I was the complexity of implementation.   It's difficult for me to follow this code.

Why does the data need to be processed twice?  I don't think it does.  The use of lambda is _much_ slower than helper methods, too.

<pre>
  >> def foo; end
  => nil
  >> t = Time.now; 10000.times { foo }; p Time.now - t
  => 0.002709
  => nil
  >> bar = lambda {}
  => #<Proc:0x00000000@(irb):9>
  >> t = Time.now; 10000.times { bar.call }; Time.now - t
  => 0.007569
</pre>


I know these issues may seem trivial for a couple hundred records, but Prawn needs to be able to chew through hundreds of thousands.   Admittedly, I have not benchmarked.

**Comment by blaxter** [comment]
The lambdas are only to not repeat code, if you think they are a problem for performance, I'll remove all of them.

I thought you were talking about the second loop, I did it because when you have a colspan cell, this means that its width could affect several column's widths. When the total width of the colspan cell is bigger than the sum of the columns affected, you should increase the width of those columns in a proportional way. (e.g. @columns_width = [10, 20, 30], in the position 0 (of some row) there is a colspan row with a width of 35, @columns_width should be now [13, 22, 30 ], but in the new row if there is a plain cell in position 0 with width = 14, you should update @columns_width to [ 15, 20, 30 ])

You can do this in a single loop, of course, but it'd be so much complicated because you have to take care, when updating @column_widths, that in previous rows you had proccessed a colspan row, so you should decrease and recalculate widths, and there are some ugly cases that require to do more work (e.g., when you have several colspan cells one after the other), so I decided to make two iterations because that way it's so much simple, almost trivial, and premature optimization is the root of all evil, or something like that they say. 

But I'm going to change that to something like this:
    first_loop do
       if cell_with_rowspan
          cells_with_rowspan_to_process << [ cell ]
       else
          do stuff
       end
    end
    cells_with_rowspan_to_process.each do |cell|
       do_the_work_for_rowspan_cells
    end

**Comment by practicingruby** [comment]
It's good to not repeat the code, but it's fine to just make private methods for that.

I think the approach of just identifying the cells that need to be processed is a good one, and is amenable to having a helper method then.   first_loop {    }; adjust_for_colspan(cells), or whatever.

You keep typing row_span instead of colspan, including in your tests.  Please avoid that :)

Anyway, can you add an example to the bugs/ directory that shows what your second patch fixes?  I understand the specs but it'd be a lot easier if I could just look at a broken PDF.

**Comment by practicingruby** [comment]
Also, it is _NOT_ premature optimization.  Table is much slower than I want it to be.  I don't want to make it even slightly more slow if I can avoid it.
